<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>69b1398e-960b-41bf-a99c-e2904e8ac850</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="tessdata\dan.traineddata" />
    <None Remove="tessdata\eng.traineddata" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Dockerfile" />
    <Content Include="tessdata\dan.traineddata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="tessdata\eng.traineddata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RagAPI.Core\RagAPI.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="GgufModels\mmproj-Qwen2.5-VL-7B-Instruct-f16.gguf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="GgufModels\Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="GgufModels\qwen3-8b-q4_k_m.gguf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="GgufModels\qwen3-embedding-4b-q4_k_m.gguf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
